source 'https://rubygems.org'

gem 'berkshelf',  '~> 3.1.3'
gem 'chef',       '~> 11.12.2'
gem 'chefspec',   '~> 3.4'
gem 'foodcritic', '~> 3.0'
gem 'rake'
gem 'rubocop'
gem 'rspec',      '~> 2.14.0'
gem 'git-precommit'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-kitchen'
  gem 'guard-rubocop'
  gem 'guard-foodcritic'
  gem 'ruby_gntp'
  gem 'travis', '~> 1.6.14'
  gem 'unf'
end

group :cloud do
  gem 'kitchen-ec2'
end

group :integration do
  gem 'test-kitchen', '~> 1.0'
  gem 'kitchen-vagrant'
  gem 'kitchen-docker'
end
