#!/usr/bin/env rake
require 'foodcritic'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'kitchen'
require 'git-precommit/tasks'

# default task
task :default => [:help]

# General tasks
task :help do
  puts 'usage:'
  puts '--------------------------------'
  puts ''
  puts 'Style and Lint Tasks'
  puts '  rake lint -- Runs RuboCop'
  puts '  rake rubocop -- Runs static code analysis and style guide check'
  puts '  rake foodcritic -- Lint tool for Opscode Chef Cookbooks'
  puts ''
  puts '  rake integration -- Runs integration tests, defaults to using Vagrant as the environment'
  puts '  rake integration:cloud -- Runs integration tests using an EC2 VM'
  puts '  rake integration:vagrant -- Runs integration tests using a Vagrant VM'
  puts ''
  puts '  rake travis -- Travis default command, runs lint, spec, and cloud integration tests'
  puts ''
  puts '  rake test -- Runs the chef spec tests'
  puts '  rake spec -- Runs Cookbook unit tests'
end

# --------------------------------
# :lint tasks
# --------------------------------

# Lint the cookbook
desc 'Run linters'
task :lint => [:rubocop, :foodcritic]

# Foodcritic
desc 'Run foodcritic lint checks'
task :foodcritic do
  if Gem::Version.new('1.9.2') <= Gem::Version.new(RUBY_VERSION.dup)
    puts 'Running Foodcritic tests...'
    FoodCritic::Rake::LintTask.new do |t|
      t.options = { :fail_tags => ['any'] }
      puts 'done.'
    end
  else
    puts 'WARN: foodcritic run is skipped as Ruby #{RUBY_VERSION} is < 1.9.2.'
  end
end

# RuboCop
desc 'Run RuboCop lint checks'
task :rubocop do
  RuboCop::RakeTask.new
end

# --------------------------------
# :integration tasks -- Defaults to Vagrant
# --------------------------------
desc 'Integration tests using Vagrant and Test Kitchen'
task :integration => ['lint', 'integration:vagrant']

# Integration tests w/ Kitchen
namespace :integration do

  desc 'Test Kitchen using EC2 Cloud'
  task :cloud do
    run_kitchen = true

    if !ENV.key?('AWS_ACCESS_KEY_ID') ||
       !ENV.key?('AWS_SECRET_ACCESS_KEY') ||
       !ENV.key?('AWS_KEYPAIR_NAME') ||
       !ENV.key?('AWS_USERNAME') ||
       !ENV.key?('AWS_SECURITY_GROUPS') ||
       !ENV.key?('LOCAL_SSH_KEY_FILE_FOR_EC2')

      if !ENV.key?('TRAVIS')
        puts 'AWS Environment variables not set, make sure to run source cloud-config/ec2-config.conf'
      else
        puts 'Secure Environment variables not set, Pull Requests from forks do not support cloud builds.'
      end

      run_kitchen = false
    end

    if run_kitchen
      Kitchen.logger = Kitchen.default_file_logger
      @loader = Kitchen::Loader::YAML.new(:project_config => './.kitchen.cloud.yml')
      config = Kitchen::Config.new(:loader => @loader)
      config.instances.each do |instance|
        instance.test(:always)
      end
    end
  end

  desc 'Test Kitchen using Vagrant'
  task :vagrant do
    Kitchen.logger = Kitchen.default_file_logger
    Kitchen::Config.new.instances.each do |instance|
      instance.test(:always)
    end
  end
end

# Test the cookbook
desc 'Run lint and spec'
task :test => [:lint, :spec]

# RSpec
desc 'Run chefspec tests'
task :spec do
  puts 'Running Chefspec tests'
  RSpec::Core::RakeTask.new(:spec)
end

# Travis Default Commands
desc 'Run Travis build'
task :travis => ['test', 'integration:cloud']

# Precommit
desc 'Run git-precommit'
task :precommit => [:test]
