<?php
/**
 *
 * @link https://github.com/oakensoul/application-skeleton for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr. and Project Contributors
 * http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package application-skeleton
 */
?>

<div class="container">
	<div class="starter-template">
		<h1>Bootstrap starter template</h1>
		<p class="lead">
			Use this document as a way to quickly start any new project.<br> All
			you get is this text and a mostly barebones HTML document.
		</p>
	</div>
</div>
