<?php
/**
 *
 * @link https://github.com/web-masons/application-blueprint for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr. and Project Contributors
 * http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package application-skeleton
 */

/*
 * Working with Views
 *
 * This view won't get seen unless you configure ZF2 to see it in the application stack by
 * adding a line something akin to the following in your module configuration:
 *
 * $view_manager = array (
 *   'template_map' => array (
 *     'application/index/index' => __DIR__ . '/../view/application/index/index.phtml'
 *   ),
 *   'template_path_stack' => array (
 *     __DIR__ . '/../view'
 *   )
 * );
 *
 * More information on view can be found here:
 * http://framework.zend.com/manual/2.2/en/modules/zend.view.quick-start.html
 */
