<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
?>

<div class="theme-header" id="content">
	<div class="container">
		<h1>Application Skeleton</h1>
		<p>A ZF2 base application built off of my Cornerstone module. This
			application can be used for isolated module development as well as
			new site development.</p>

		<div id="adblock-container">
			<div class="adblock">
				<span class="adblock-image"><a href="http://github.com/oakensoul/"
					title="Fork Us on GitHub!" target="_blank"> <img
						class="adblock-image adblock-img"
						src="/theme/oakensoul/img/repo.png" title="Fork Us on GitHub!"
						alt="Fork Us on GitHub!" border="0" width="120"></a></span>

				<div class="adblock-text">
					<h4>Fork Us on GitHub!</h4>
					<ul class="no-glyph">
						<li><i class='icon-github'> </i> <a
							href="http://github.com/oakensoul/application-skeleton/">Application
								Skeleton</a></li>
						<li><i class='icon-github'> </i> <a
							href="http://github.com/oakensoul/Cornerstone/">Cornerstone</a></li>
						<li><i class='icon-github'> </i> <a
							href="http://github.com/oakensoul/DataModeling/">DataModeling</a></li>
					</ul>
				</div>

			</div>
		</div>
	</div>
</div>